// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using feedBackMvc.Models;

#nullable disable

namespace feedBackMvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240819102241_IN_ThongTinNguoiBenhModel")]
    partial class IN_ThongTinNguoiBenhModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("feedBackMvc.Models.Admins", b =>
                {
                    b.Property<int>("idAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idAdmin"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.HasKey("idAdmin");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("feedBackMvc.Models.IN_CauHoiKhaoSat", b =>
                {
                    b.Property<int>("IdIN_CauHoiKhaoSat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdIN_CauHoiKhaoSat"));

                    b.Property<string>("CauHoi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdIN_NhomCauHoiKhaoSat")
                        .HasColumnType("integer");

                    b.Property<char?>("TieuDeCauHoi")
                        .IsRequired()
                        .HasColumnType("character(1)");

                    b.HasKey("IdIN_CauHoiKhaoSat");

                    b.HasIndex("IdIN_NhomCauHoiKhaoSat");

                    b.HasIndex("TieuDeCauHoi")
                        .IsUnique();

                    b.ToTable("IN_CauHoiKhaoSat");
                });

            modelBuilder.Entity("feedBackMvc.Models.IN_MauKhaoSat", b =>
                {
                    b.Property<int>("IdIN_MauKhaoSat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdIN_MauKhaoSat"));

                    b.Property<string[]>("CauHoiKhaoSat")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string[]>("NhomCauHoiKhaoSat")
                        .HasColumnType("text[]");

                    b.Property<string>("TenMauKhaoSat")
                        .HasColumnType("text");

                    b.Property<int>("idAdmin")
                        .HasColumnType("integer");

                    b.HasKey("IdIN_MauKhaoSat");

                    b.HasIndex("idAdmin");

                    b.ToTable("IN_MauKhaoSat");
                });

            modelBuilder.Entity("feedBackMvc.Models.IN_NhomCauHoiKhaoSat", b =>
                {
                    b.Property<int>("IdIN_NhomCauHoiKhaoSat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdIN_NhomCauHoiKhaoSat"));

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char?>("TieuDe")
                        .IsRequired()
                        .HasColumnType("character(1)");

                    b.Property<int>("idAdmin")
                        .HasColumnType("integer");

                    b.HasKey("IdIN_NhomCauHoiKhaoSat");

                    b.HasIndex("TieuDe")
                        .IsUnique();

                    b.HasIndex("idAdmin");

                    b.ToTable("IN_NhomCauHoiKhaoSat");
                });

            modelBuilder.Entity("feedBackMvc.Models.IN_ThongTinNguoiBenh", b =>
                {
                    b.Property<int>("IdIN_ThongTinNguoiBenh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdIN_ThongTinNguoiBenh"));

                    b.Property<bool?>("CoSuDungBHYT")
                        .HasColumnType("boolean");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("text");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoNgayNamVien")
                        .HasColumnType("text");

                    b.Property<int?>("Tuoi")
                        .HasColumnType("integer");

                    b.HasKey("IdIN_ThongTinNguoiBenh");

                    b.ToTable("IN_ThongTinNguoiBenh");
                });

            modelBuilder.Entity("feedBackMvc.Models.IN_CauHoiKhaoSat", b =>
                {
                    b.HasOne("feedBackMvc.Models.IN_NhomCauHoiKhaoSat", "NhomCauHoiKhaoSat")
                        .WithMany()
                        .HasForeignKey("IdIN_NhomCauHoiKhaoSat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhomCauHoiKhaoSat");
                });

            modelBuilder.Entity("feedBackMvc.Models.IN_MauKhaoSat", b =>
                {
                    b.HasOne("feedBackMvc.Models.Admins", "admins")
                        .WithMany()
                        .HasForeignKey("idAdmin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("admins");
                });

            modelBuilder.Entity("feedBackMvc.Models.IN_NhomCauHoiKhaoSat", b =>
                {
                    b.HasOne("feedBackMvc.Models.Admins", "admins")
                        .WithMany()
                        .HasForeignKey("idAdmin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("admins");
                });
#pragma warning restore 612, 618
        }
    }
}
